image: golang:1.10-rc-alpine
stages:
  - test
before_script:
  - mkdir -p /go/src/gitlab.com
  - ln -s /builds/user /go/src/gitlab.com/user
coverage:
  stage: test
  script:
    - apk add --no-cache git build-base
    - cd /go/src/gitlab.com/user/project
    - go get ./...
    - go test $(go list ./... | grep -v /vendor/) -v -coverprofile .testCoverage.txt